# Build targets for native compilation on GitHub runners
#
# Format:
#   os: Operating system (linux, darwin, windows)
#   arch: Architecture matching the GitHub runner (x86_64, aarch64)
#   compiler: Compiler to use (clang++ for C++, msvc on Windows)
#   build_system: Build system to use (cmake)
#
# Note: Each target is built natively on its corresponding GitHub runner.
# Cross-compilation is not supported due to OS-specific library dependencies.
#
# GitHub runner architectures:
#   - Linux: x86_64 only (ubuntu-latest)
#   - macOS: x86_64 (macos-13) and aarch64 (macos-latest/macos-14)
#   - Windows: x86_64 only (windows-latest)

targets:
  # Linux x86_64 (ubuntu-latest runner)
  - os: linux
    arch: x86_64
    compiler: clang++
    build_system: cmake

  # macOS aarch64 (macos-latest / macos-14 runner - Apple Silicon)
  - os: darwin
    arch: aarch64
    compiler: clang++
    build_system: cmake

  # Windows x86_64 (windows-latest runner)
  - os: windows
    arch: x86_64
    compiler: clang++
    build_system: cmake
