version: "3"

vars:
  CPP_PROJECT_NAME: '{{default .CPP_PROJECT_NAME "cpp-template"}}'
  CPP_BUILD_SYSTEM: '{{default .CPP_BUILD_SYSTEM "cmake"}}'
  CPP_BUILD_DIR: '{{default .CPP_BUILD_DIR "build"}}'
  CPP_BUILD_TYPE: '{{default .CPP_BUILD_TYPE "Release"}}'
  CPP_COMPILER: '{{default .CPP_COMPILER "clang++"}}'
  CPP_LINTER: '{{default .CPP_LINTER "clang-tidy"}}'
  CPP_FORMATTER: '{{default .CPP_FORMATTER "clang-format"}}'

tasks:
  # ==========================================================================
  # Build Tasks
  # ==========================================================================

  build:
    desc: "Build project (build-system: {{.CPP_BUILD_SYSTEM}}, type: {{.CPP_BUILD_TYPE}})"
    cmds:
      - task: "build:{{.CPP_BUILD_SYSTEM}}"
    sources:
      - src/**/*.cpp
      - src/**/*.hpp
      - include/**/*.hpp
      - include/**/*.h
      - tests/**/*.cpp

  build:cmake:
    desc: "Build project using CMake"
    sources:
      - CMakeLists.txt
      - tests/CMakeLists.txt
    generates:
      - "{{.CPP_BUILD_DIR}}/CMakeCache.txt"
      - "{{.CPP_BUILD_DIR}}/compile_commands.json"
    cmds:
      - mise run build

  build:xmake:
    desc: "Build project using XMake"
    sources:
      - xmake.lua
    generates:
      - .xmake/cache/config
      - "{{.CPP_BUILD_DIR}}/compile_commands.json"
    cmds:
      - mise run build

  build:debug:
    desc: "Build project in Debug Mode (default: {{.CPP_BUILD_SYSTEM}})"
    cmds:
      - task: "build:debug:{{.CPP_BUILD_SYSTEM}}"
    sources:
      - src/**/*.cpp
      - src/**/*.hpp
      - include/**/*.hpp
      - include/**/*.h
      - tests/**/*.cpp

  build:debug:cmake:
    desc: "Build project in Debug Mode using CMake"
    sources:
      - CMakeLists.txt
      - tests/CMakeLists.txt
    generates:
      - "{{.CPP_BUILD_DIR}}/CMakeCache.txt"
      - "{{.CPP_BUILD_DIR}}/compile_commands.json"
    cmds:
      - mise run build:debug

  build:debug:xmake:
    desc: "Build project in Debug Mode using XMake"
    sources:
      - xmake.lua
    generates:
      - .xmake/cache/config
      - "{{.CPP_BUILD_DIR}}/compile_commands.json"
    cmds:
      - mise run build:debug

  # ============================================================================
  # Clean Tasks
  # ============================================================================

  clean:
    cmds:
      - for:
          - '.jscpd/html'
          - '.task'
          - '.xmake'
          - '{{.CPP_BUILD_DIR}}'
          - 'docs'
          - 'node_modules'
          - 'package-lock.json'
        cmd: rm -rf {{.ITEM}}
    desc: "Clean all builds"

  # docs:
  #   desc: "Generate documentation with Doxygen"
  #   deps:
  #     - task: which
  #       vars:
  #         COMMAND: "doxygen"
  #   cmds:
  #     - doxygen Doxyfile

  # duplicate-check:
  #   desc: "Check for duplicate code using jscpd"
  #   deps:
  #     - task: which
  #       vars:
  #         COMMAND: "node"
  #   cmds:
  #     - cmd: |
  #         [ ! -d ./node_modules ] && npm install jscpd  @jscpd/badge-reporter

  #         mise exec -- npx jscpd src/ include/

  #         git add .jscpd/jscpd-badge.svg 2>/dev/null || true

  format:
    desc: "Format code using {{.CPP_FORMATTER}}"
    deps:
      - task: venv
      - task: format:check
        vars:
          CLI_ARGS: fix

  format:check:
    desc: "Check code formatting"
    deps:
      - task: venv
    cmds:
      - cmd: ./.venv/bin/python scripts/format.py {{.CLI_ARGS}}
        platforms: [darwin, linux]
      - cmd: ./.venv/Scripts/python scripts/format.py {{.CLI_ARGS}}
        platforms: [windows]

  lint:
    desc: "Run {{.CPP_LINTER}} linter and fix issues"
    cmds:
      - cmd: mise run lint

  lint:check:
    desc: "Run {{.CPP_LINTER}} linter without fixing"
    cmds:
      - cmd: mise run lint:check

  test:
    desc: "Run tests (default: {{.CPP_BUILD_SYSTEM}})"
    cmds:
      - task: build
      - task: test:{{.CPP_BUILD_SYSTEM}}

  test:cmake:
    desc: "Run tests using CMake"
    cmds:
      - mise run test

  # test:watch:
  #   desc: "Run tests in watch mode (manual restart)"
  #   cmds:
  #     - |
  #       echo "🔄 Watch mode: Press Ctrl+C to stop, then run 'task test' to re-run tests"
  #       echo "💡 Consider using entr for automatic file watching:"
  #       echo "    find src tests -name '*.cpp' -o -name '*.hpp' | entr -c task test"
  #       task test

  test:xmake:
    desc: "Run tests using XMake"
    cmds:
      - mise run test

  validate:
    desc: "Run integration tests"
    cmds:
      - cmd: mise install
      - for:
          - cmake
          - xmake
        task: validate:by:build-system
        vars:
          CPP_BUILD_SYSTEM: "{{.ITEM}}"

  validate:by:build-system:
    desc: "Run CI pipeline (format, lint, duplicate-check, test)"
    cmds:
      - task: clean
      # - task: "format:check"
      # - task: "duplicate-check"
      # - task: "lint:check"
      - task: "test"
      - task: "build"
      - cmd: ./build/**/{{.CPP_PROJECT_NAME}}
      - cmd: echo "✓ Integration test passed for {{.CPP_BUILD_SYSTEM}}"

  # valgrind:
  #   desc: "Run application with Valgrind"
  #   deps:
  #     - task: which
  #       vars:
  #         COMMAND: "valgrind"
  #     - task: build
  #       vars: { CPP_BUILD_TYPE: "Debug" }
  #   cmds:
  #     - mise exec -- valgrind --leak-check=full --show-leak-kinds=all ./{{.CPP_BUILD_DIR}}/src/{{.CPP_PROJECT_NAME}}

  # which:
  #   desc: "Check if at least one command exists"
  #   deps:
  #     - task: venv
  #   cmds:
  #     - cmd: mise exec -- ./.venv/bin/python scripts/which.py {{if .COMMANDS}}{{.COMMANDS}}{{else}}{{.COMMAND}}{{end}}
  #       platforms: [darwin, linux]
  #     - cmd: mise exec -- ./.venv/Scripts/python scripts/which.py {{if .COMMANDS}}{{.COMMANDS}}{{else}}{{.COMMAND}}{{end}}
  #       platforms: [windows]

  # venv:
  #   cmds:
  #     - cmd: |
  #         mise exec -- uv venv
  #   desc: "Create or update Python virtual environment in .venv"
  #   silent: true
