name: 'Setup Development Tools'
description: 'Install Task, mise, and project tools with caching'
runs:
  using: 'composite'
  steps:
    - name: Setup Task
      uses: go-task/setup-task@v1

    - name: Install Mise (Darwin & Linux)
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        curl https://mise.run | sh
        echo "eval \"\$(/Users/runner/.local/bin/mise activate bash)\"" >> ~/.bashrc
        mise activate
        mise self-update
        mise --version

    - name: Install Mise (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        choco install mise
        powershell -NoProfile -ExecutionPolicy Bypass -Command "mise self-update"
        powershell -NoProfile -ExecutionPolicy Bypass -Command "mise --version"


    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-mise-tools-${{ hashFiles('.mise.toml') }}
        path: |
          ~/.local/share/mise
          ~/.cache/mise
          ~/.venv

    - run: sudo apt install -y build-essential lcov
      if: ${{ runner.os == 'Linux' }}
      shell: bash

    - run: brew install gcc lcov
      if: ${{ runner.os == 'macOS' }}
      shell: bash

    - name: Install mise tools
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        mise install --yes
        mise run uv:sync
